server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        register-enabled: false
    gateway:
      routes:
        - id: app-provider-route
          # 注意使用lb负载均衡语法，必须有注册中心以及负载均衡模块依赖
          uri: lb://app-provider
          predicates:
            - Path=/app-provider/**
          filters:
            - RewritePath=/app-provide/?(?<segment>.*), /$\{segment}
            # 或者使用下面这个
            #- StripPrefix=1
        - id: app-consumer-route
          uri: lb://app-consumer
          predicates:
            - Path=/app-consumer/**
          filters:
            - RewritePath=/app-consumer/?(?<segment>.*), /$\{segment}